import React, { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import styles from './Work.module.css';

gsap.registerPlugin(ScrollTrigger);

const projects = [
  {
    id: 1,
    title: 'Kisaan Sevak',
    category: 'AgriTech Platform',
    description: 'Voice-First AI Farm Assistant. Empowering Indian farmers with real-time market data, AI insights, and hyperlocal community alerts.',
    image: '/kisaan1.png',
    tags: ['React', 'Neon DB', 'Firebase', 'OpenRouter'],
    color: '#10b981',
    longDescription: 'Kisaan Sevak is a full-stack AgriTech platform built for Indian farmers. It solves the information gap between farmers and markets by providing live mandi prices from the Agmarknet API, AI-powered sell/hold recommendations generated by LLMs, a hyperlocal farmer community with real-time SSE updates, and government scheme discovery. Built with a mobile-first approach, it features complete multi-language support (English, Hindi, Kannada) directly integrated with AI outputs.',
    features: [
      'Mandi Mitra: Live crop prices with an AI Market Copilot providing sell/hold recommendations.',
      'Kisaan Network: Real-time SSE feed with voice posting and AI post enhancement.',
      'Crop Doctor: AI leaf disease diagnosis with voice playback.',
      'Sarkar Saathi: Government schemes matching based on land size and crop.',
      'Waste to Wealth: Farm residue marketplace with live bidding.'
    ]
  },
  {
    id: 2,
    title: 'Nexus Commerce',
    category: 'E-Commerce',
    description: 'High-performance storefront with immersive 3D product previews and seamless checkout experience.',
    image: 'https://images.unsplash.com/photo-1600521605536-31c3be313c00?q=80&w=1200&auto=format&fit=crop',
    tags: ['Next.js', 'Three.js', 'Stripe'],
    color: '#ec4899',
    longDescription: 'A futuristic e-commerce platform designed to push the boundaries of web experiences. It features immersive 3D product previews powered by WebGL, allowing users to interact with products in real-time before purchase. The checkout flow is highly optimized and seamlessly integrated with modern payment gateways.',
    features: [
      'Interactive 3D product configurator.',
      'Lightning-fast SSR and static generation via Next.js.',
      'Secure, one-click checkout experience.',
      'Real-time inventory and order tracking.'
    ]
  },
  {
    id: 3,
    title: 'Lumina Dashboard',
    category: 'Data Visualization',
    description: 'Real-time analytics dashboard with dynamic charts and dark mode optimized for late-night deep work.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1200&auto=format&fit=crop',
    tags: ['Vue', 'D3.js', 'Tailwind'],
    color: '#6366f1',
    longDescription: 'Lumina is an enterprise-grade analytics dashboard that translates complex datasets into beautiful, comprehensible visual stories. Built heavily on D3.js, it offers fluid animations, responsive layouts, and a meticulously crafted dark mode that reduces eye strain for power users.',
    features: [
      'Custom SVG charting engine with D3.',
      'WebSocket integration for live data streaming.',
      'Fully customizable dashboard layouts with drag-and-drop.',
      'Granular role-based access control (RBAC).'
    ]
  },
  {
    id: 4,
    title: 'Oasis Social',
    category: 'Web App',
    description: 'A decentralized social network prioritizing user privacy and ad-free content consumption.',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    tags: ['Svelte', 'Node.js', 'Web3'],
    color: '#f59e0b',
    longDescription: 'Oasis rethinks social media by prioritizing mental health and data privacy. Running on decentralized protocols, users fully own their data. The UI is completely ad-free and algorithmic feeds are replaced by chronological, community-driven content discovery.',
    features: [
      'Decentralized identity and data storage.',
      'End-to-end encrypted direct messaging.',
      'Ad-free, chronologically sorted feeds.',
      'Community-governed content moderation.'
    ]
  }
];

export default function Work() {
  const containerRef = useRef(null);
  const cardsRef = useRef([]);
  const [selectedProject, setSelectedProject] = useState(null);

  useEffect(() => {
    let ctx = gsap.context(() => {
      cardsRef.current.forEach((card, index) => {
        const baseProps = { 
          xPercent: -50, 
          yPercent: -50, 
          left: "50%", 
          top: "55%", 
          zIndex: projects.length - index 
        };
        if (index === 0) {
          gsap.set(card, { ...baseProps, scale: 1, opacity: 1 });
        } else {
          gsap.set(card, { ...baseProps, scale: 0.5, opacity: 0, filter: 'blur(10px)' });
        }
      });

      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: containerRef.current,
          start: "top top",
          end: `+=${projects.length * 100}%`,
          pin: true,
          scrub: 1,
        }
      });

      cardsRef.current.forEach((card, index) => {
        if (index < cardsRef.current.length - 1) {
          const nextCard = cardsRef.current[index + 1];

          tl.to(card, {
            scale: 2.5,
            opacity: 0,
            filter: 'blur(20px)',
            duration: 1,
            ease: "power2.inOut"
          }, index);

          tl.to(nextCard, {
            scale: 1,
            opacity: 1,
            filter: 'blur(0px)',
            duration: 1,
            ease: "power2.inOut"
          }, index);
        }
      });
    }, containerRef);

    return () => ctx.revert();
  }, []);

  return (
    <>
      <section id="work" className={styles.workPage} ref={containerRef}>
        <div className={styles.header}>
          <p className={styles.label}>// portfolio</p>
          <h2 className={styles.title}>
            My <span className={styles.accent}>Work</span>
          </h2>
        </div>

        <div className={styles.cardsContainer}>
          {projects.map((project, index) => (
            <div 
              key={project.id} 
              className={styles.slide}
              ref={el => cardsRef.current[index] = el}
            >
              <div className={styles.heroImageWrapper}>
                <img src={project.image} alt={project.title} className={styles.heroImage} />
                <div className={styles.imageGlow} style={{ backgroundColor: project.color }} />
              </div>
              
              <div className={styles.refinedDetails}>
                <div className={styles.detailCol}>
                  <span className={styles.miniLabel}>Project 0{index + 1}</span>
                  <h3 className={styles.cleanTitle}>{project.title}</h3>
                </div>
                
                <div className={styles.detailColMain}>
                  <span className={styles.miniLabel}>{project.category}</span>
                  <p className={styles.cleanDesc}>{project.description}</p>
                </div>
                
                <div className={styles.detailColRight}>
                  <span className={styles.miniLabel}>Details</span>
                  <button 
                    className={styles.appleButton}
                    onClick={() => setSelectedProject(project)}
                  >
                    View Details
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Project Details Modal */}
      {selectedProject && createPortal(
        <div className={styles.modalOverlay} onClick={() => setSelectedProject(null)}>
          <div className={styles.modalContent} onClick={e => e.stopPropagation()}>
            <div className={styles.modalHeader}>
              <div className={styles.modalGlow} style={{ backgroundColor: selectedProject.color }} />
              <img src={selectedProject.image} className={styles.modalImage} alt={selectedProject.title} />
            </div>
            
            <div className={styles.modalBody}>
              <button className={styles.closeBtnText} onClick={() => setSelectedProject(null)}>
                ✕ <span>GO BACK</span>
              </button>
              <h2 className={styles.modalTitle}>{selectedProject.title}</h2>
              <p className={styles.modalCategory} style={{ color: selectedProject.color }}>
                {selectedProject.category}
              </p>
              
              <div className={styles.modalText}>
                <p>{selectedProject.longDescription}</p>
                
                {selectedProject.features && (
                  <>
                    <h4>Key Features</h4>
                    <ul>
                      {selectedProject.features.map((feature, i) => (
                        <li key={i}>{feature}</li>
                      ))}
                    </ul>
                  </>
                )}
              </div>
              
              <div className={styles.modalTags}>
                {selectedProject.tags.map(t => (
                  <span key={t} className={styles.modalTag}>{t}</span>
                ))}
              </div>
            </div>
          </div>
        </div>,
        document.body
      )}
    </>
  );
}